### PR TITLE
Reject invalid url slugs

### LINKED ISSUE #222: Invalid `url` values are not caught
When specifying a `url` for a page in its yaml header, some values will fail silently. For example:

```markdown
---
# index.md

url: 0
---

# Hello world
```

This page will be built as `_site/index.md`. I believe that this is because the top-level checks that happen on the `url` value are to see if it is `false` or has `typeof string` or `typeof function`. https://github.com/lumeland/lume/blob/8e6bb7b112861b2699a37d89501aeb000768298f/core/renderer.ts#L175-L220

Because values like `0` are parsed as numbers, they fail these conditions (thereby bypassing the validation that happens for strings) and end up with the default `url`.[^1] My assumption is that this is not the desired behaviour?

Do you have a sense of what the desired behaviour would be, here? I'm not sure whether it would be better for it to crash, or to warn the user, or to coerce the value to a string. But if you have a view on what the desired behaviour should be, I'd be happy to try and write up a PR to implement it.

[^1]: Similarly, if an array is provided as the `url` value, this will also fail silently and the page will be built with its default url.

### PR DESCRIPTION
**Pull request by bryophyta**
## What

Adds a check in `renderer` to make sure that the `url` provided is of a valid type. Throws an error if it is not.

## Why

Previously, the checks were structured so that if an invalid type was provided (e.g. a `number` or `array`) then the rendered would 'fail silently', falling back onto the default url scheme without warning the user. (Closes #222.)

## Testing

I've checked it locally against a few different values. Is this something you'd like unit tests for? I haven't written any here because I'm not familiar with the testing library etc., but I'm happy to spend some time trying to work it out if you'd like a test for it.

### CODE REVIEW

File: core/renderer.ts [hunk 1]
```diff
@@ -180,6 +180,14 @@ export default class Renderer {
       return;
     }
 
+    // Check that `url` is of a valid type
+    if (!["string", "function", "undefined"].includes(typeof url)) {
```
Comment (oscarotero) [inline core/renderer.ts:184]: This doesn't check the value returned when the url is a function, so a function that returns an integer would fail silently. I think the following flow works better:

```js
// Execute the function
if (typeof url === "function") {
  url = url(page);
}

if (typeof url === "string") {
  // The current code for strings
} else if (url !== undefined) {
  // throws an exception because the url is not valid
} else if (!this.formats.get(page.src.ext || "")?.asset) {
  // The current code for undefined url
}
```

**Review by oscarotero — CHANGES_REQUESTED** [review]

File: core/renderer.ts (hunk 1 above)
Comment (bryophyta) [reply core/renderer.ts:184]: ah yes, got it! I was thinking of keeping the type validation closer to the edge, but had forgotten that the function's return type isn't enforced at runtime. Your suggested alternative sounds good to me 👍

**Comment by bryophyta** [comment]
I've made the requested updates now, hope it looks alright!

**Comment by oscarotero** [comment]
Perfect. thanks!
